apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 1m
    failureLimit: 5
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://argo-prometheus-server.saiteja:80
        query: |
          sum(prometheus_http_request_duration_seconds_count{handler="/-/ready"}) /
          sum(prometheus_http_request_duration_seconds_count{handler="/graph"})
