apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 3m
    failureLimit: 30
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://argo-prometheus-server:80
        query: |
          sum
          sum(irate(nginx_ingress_controller_requests{service=~"{{args.service-name}}",status!~"[4-5].*"}[5m])) /
          sum(irate(nginx_ingress_controller_requests{service=~"{{args.service-name}}"}[5m]))
